services:
  app:
    build:
      context: .
    container_name: my-poetry-dev-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud:ro
    working_dir: /app  
    command: poetry run streamlit run app/main.py