services:
  app:
    build:
      context: .
    container_name: AI-AGENT-HACKATHON-APP-PROD
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    working_dir: /app
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud:ro
   
    command: poetry run streamlit run app/main.py --server.port=8080 --server.address=0.0.0.0
