name: Update requirements.txt on Merge

on:
  push:
    branches:
      - main
      - develop

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Make
        run: |
          sudo apt-get install make

      - name: Install dependencies and update requirements.txt
        run: |
          make requirements-update

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add requirements.txt
          git diff --cached --exit-code || (git commit -m "chore: update requirements.txt" && git push)
